obs:
  password: "aaabbbccc"
  host: "192.168.2.122"
  port: 4455
  scene:
    ToolChanging: ToolChangingScene
    Printing: PrintingScene
printer:
  host: "192.168.2.115"
  moonracker_port: 7125
software:
  debug_level: "INFO"